steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'source ./setenv.sh']
- name: 'bash'
  args: ['printenv']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'stop', '${_VMNAME}', '--zone=${_ZONE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'start', '${_VMNAME}', '--zone=${_ZONE}']
timeout: 600s
tags: ['mytag1', 'mytag2']
